version: '3'

services:
  app:
    build: ./
    restart: always
    ports:
      - 5000:80
    env_file:
      - app.env
    depends_on:
      - postgres
    volumes:
      - static:/app/app/static

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=db_database
      - POSTGRES_USER=db_user
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  static:
  postgres:
