services:
  app:
    build: ./
    restart: always
    ports:
      - 5000:80
    env_file:
      - app.env
    environment:
      - GUNICORN_CONF=/app/gunicorn_conf_dev.py
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app
      - uploads:/app/app/static/uploads

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=db_database
      - POSTGRES_USER=db_user
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./:/app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U db_user -d db_database" ]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  uploads:
  postgres:
