"""Add categories to questions

Revision ID: 23c87f39cb4a
Revises: 103601ff4331
Create Date: 2022-06-27 12:06:46.503887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c87f39cb4a'
down_revision = '103601ff4331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('question', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'category_id')
    op.drop_table('category')
    # ### end Alembic commands ###
