"""Add cool learning group db.

Revision ID: 57347e33eb87
Revises: 8214912a9c5a
Create Date: 2022-04-13 09:47:21.000350

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "57347e33eb87"
down_revision = "8214912a9c5a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ab_user", sa.Column("learning_group_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "ab_user", "learning_group", ["learning_group_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ab_user", type_="foreignkey")
    op.drop_column("ab_user", "learning_group_id")
    # ### end Alembic commands ###
