"""empty message

Revision ID: 62a26de10677
Revises: 68bd08372eac
Create Date: 2022-09-05 21:10:04.369582

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "62a26de10677"
down_revision = "68bd08372eac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ab_register_user", sa.Column("role", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ab_register_user", "role")
    # ### end Alembic commands ###
