"""Add share_token to assignment

Revision ID: 6562a313095a
Revises: abc5ce433382
Create Date: 2025-01-12 12:25:55.519401

"""
from alembic import op
import sqlalchemy as sa
import secrets
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = '6562a313095a'
down_revision = 'abc5ce433382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('share_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###

    # Create table representation
    assignment_table = table('assignment',
        column('id', sa.Integer),
        column('share_token', sa.String)
    )

    # Generate and update share_tokens
    connection = op.get_bind()
    assignments = connection.execute(assignment_table.select()).fetchall()

    for assignment in assignments:
        connection.execute(
            assignment_table.update()
            .where(assignment_table.c.id == assignment.id)
            .values(share_token=secrets.token_urlsafe())
        )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'share_token')
    # ### end Alembic commands ###
