"""empty message

Revision ID: 68bd08372eac
Revises: 6146f25a0ac7
Create Date: 2022-09-04 11:22:54.920502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68bd08372eac'
down_revision = '6146f25a0ac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ab_user', sa.Column('password_reset_token', sa.String(length=255), nullable=True))
    op.add_column('ab_user', sa.Column('password_reset_expiration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ab_user', 'password_reset_expiration')
    op.drop_column('ab_user', 'password_reset_token')
    # ### end Alembic commands ###
