"""empty message

Revision ID: 6d83a483455a
Revises: 63ba10a926db
Create Date: 2022-08-10 13:03:59.159806

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6d83a483455a"
down_revision = "63ba10a926db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ab_user_topic")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ab_user_topic",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("topic_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topic.id"], name="ab_user_topic_topic_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["ab_user.id"], name="ab_user_topic_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="ab_user_topic_pkey"),
        sa.UniqueConstraint(
            "user_id", "topic_id", name="ab_user_topic_user_id_topic_id_key"
        ),
    )
    # ### end Alembic commands ###
