"""empty message

Revision ID: 6d86b42bc14a
Revises: 62a26de10677
Create Date: 2023-03-11 15:23:51.486541

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6d86b42bc14a"
down_revision = "62a26de10677"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "question",
        "external_id",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('question', 'external_id',
    #            existing_type=sa.String(),
    #            type_=sa.INTEGER(),
    #            existing_nullable=False)
    op.execute(
        "ALTER TABLE question ALTER COLUMN external_id TYPE INT USING external_id::integer"
    )
    # ### end Alembic commands ###
