"""empty message

Revision ID: 7205b68fa35b
Revises: 62a26de10677
Create Date: 2023-03-26 20:28:24.997466

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7205b68fa35b"
down_revision = "62a26de10677"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assoc_user_question", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "assoc_user_question", "question_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assoc_user_question", "question_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "assoc_user_question", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
