"""empty message

Revision ID: 81d2358c376c
Revises: c5818adabd98
Create Date: 2023-04-17 11:58:32.686187

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "81d2358c376c"
down_revision = "c5818adabd98"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ab_register_user", "role")
    op.add_column(
        "ab_user",
        sa.Column("email_confirmation_token", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ab_user", "email_confirmation_token")
    op.add_column(
        "ab_register_user",
        sa.Column("role", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
