"""empty message

Revision ID: 8263aeba1cc6
Revises: 90fc38d680ce
Create Date: 2022-08-31 13:44:52.641987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8263aeba1cc6"
down_revision = "90fc38d680ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assignment", sa.Column("created_on", sa.DateTime(), nullable=True))
    op.add_column("assignment", sa.Column("changed_on", sa.DateTime(), nullable=True))
    op.add_column("assignment", sa.Column("created_by_fk", sa.Integer(), nullable=True))
    op.add_column("assignment", sa.Column("changed_by_fk", sa.Integer(), nullable=True))

    op.execute("UPDATE assignment SET created_on = '2022-08-31 13:17:04.626'")
    op.execute("UPDATE assignment SET changed_on = '2022-08-31 13:17:04.626'")
    op.execute("UPDATE assignment SET created_by_fk = 1")
    op.execute("UPDATE assignment SET changed_by_fk = 1")

    op.alter_column("assignment", "created_on", nullable=False)
    op.alter_column("assignment", "changed_on", nullable=False)
    op.alter_column("assignment", "created_by_fk", nullable=False)
    op.alter_column("assignment", "changed_by_fk", nullable=False)

    op.create_foreign_key(None, "assignment", "ab_user", ["created_by_fk"], ["id"])
    op.create_foreign_key(None, "assignment", "ab_user", ["changed_by_fk"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "assignment", type_="foreignkey")
    op.drop_constraint(None, "assignment", type_="foreignkey")
    op.drop_column("assignment", "changed_by_fk")
    op.drop_column("assignment", "created_by_fk")
    op.drop_column("assignment", "changed_on")
    op.drop_column("assignment", "created_on")
    # ### end Alembic commands ###
