"""empty message

Revision ID: 90fc38d680ce
Revises: b7a5683eaacf
Create Date: 2022-08-31 12:49:50.220660

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "90fc38d680ce"
down_revision = "b7a5683eaacf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "learning_group", sa.Column("created_on", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "learning_group", sa.Column("changed_on", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "learning_group", sa.Column("created_by_fk", sa.Integer(), nullable=True)
    )
    op.add_column(
        "learning_group", sa.Column("changed_by_fk", sa.Integer(), nullable=True)
    )

    op.execute("UPDATE learning_group SET created_on = '2022-08-31 13:17:04.626'")
    op.execute("UPDATE learning_group SET changed_on = '2022-08-31 13:17:04.626'")
    op.execute("UPDATE learning_group SET created_by_fk = 1")
    op.execute("UPDATE learning_group SET changed_by_fk = 1")

    op.alter_column("learning_group", "created_on", nullable=False)
    op.alter_column("learning_group", "changed_on", nullable=False)
    op.alter_column("learning_group", "created_by_fk", nullable=False)
    op.alter_column("learning_group", "changed_by_fk", nullable=False)

    op.create_foreign_key(None, "learning_group", "ab_user", ["changed_by_fk"], ["id"])
    op.create_foreign_key(None, "learning_group", "ab_user", ["created_by_fk"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "learning_group", type_="foreignkey")
    op.drop_constraint(None, "learning_group", type_="foreignkey")
    op.drop_column("learning_group", "changed_by_fk")
    op.drop_column("learning_group", "created_by_fk")
    op.drop_column("learning_group", "changed_on")
    op.drop_column("learning_group", "created_on")
    # ### end Alembic commands ###
