"""Add video model

Revision ID: 9267092ab7ca
Revises: 12352e167092
Create Date: 2024-03-25 21:19:42.548984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9267092ab7ca'
down_revision = '12352e167092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.Enum('geogebra', 'classpad', 'nspire', name='videocategory'), nullable=False),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('ab_user', 'email',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=320),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ab_user', 'email',
               existing_type=sa.String(length=320),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_table('video')
    # ### end Alembic commands ###
