"""Make video URL mandatory

Revision ID: abc5ce433382
Revises: 9267092ab7ca
Create Date: 2024-03-25 22:06:54.892752

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "abc5ce433382"
down_revision = "9267092ab7ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("video", "video_url", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("video", "video_url", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
