"""empty message

Revision ID: b7a5683eaacf
Revises: fc01fd2c0c9a
Create Date: 2022-08-30 17:46:30.161762

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b7a5683eaacf"
down_revision = "fc01fd2c0c9a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assoc_user_learning_group",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("learning_group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learning_group_id"],
            ["learning_group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["ab_user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "learning_group_id"),
    )
    op.drop_constraint("ab_user_learning_group_id_fkey", "ab_user", type_="foreignkey")
    op.drop_column("ab_user", "learning_group_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ab_user",
        sa.Column(
            "learning_group_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "ab_user_learning_group_id_fkey",
        "ab_user",
        "learning_group",
        ["learning_group_id"],
        ["id"],
    )
    op.drop_table("assoc_user_learning_group")
    # ### end Alembic commands ###
