"""empty message

Revision ID: f46d9ee068a8
Revises: 4a52c0f07c41
Create Date: 2023-06-26 10:03:44.212737

"""

import enum

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f46d9ee068a8"
down_revision = "4a52c0f07c41"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    class SchoolType(enum.Enum):
        ahs = 1
        bhs = 2

    school_type = postgresql.ENUM(SchoolType, name="schooltype")
    school_type.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "ab_user",
        sa.Column("school_type", school_type, nullable=False, server_default="ahs"),
    )
    op.add_column(
        "category",
        sa.Column("school_type", school_type, nullable=False, server_default="ahs"),
    )
    op.add_column(
        "question",
        sa.Column("school_type", school_type, nullable=False, server_default="ahs"),
    )
    op.add_column(
        "topic",
        sa.Column("school_type", school_type, nullable=False, server_default="ahs"),
    )

    op.alter_column("ab_user", "school_type", server_default=None)
    op.alter_column("category", "school_type", server_default=None)
    op.alter_column("question", "school_type", server_default=None)
    op.alter_column("topic", "school_type", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("topic", "school_type")
    op.drop_column("question", "school_type")
    op.drop_column("category", "school_type")
    op.drop_column("ab_user", "school_type")
    # ### end Alembic commands ###
